name: CI-Release

on: [ push, pull_request ]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker Layer Caching
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: savemii-docker-cache-{hash}
          restore-keys: |
            savemii-docker-cache-
      - name: Build artifacts
        run: |
          docker build . --file Dockerfile --tag builder
          docker run --rm -v ${PWD}:/project builder make -j$(nproc)
      - name: Upload Aroma version
        uses: actions/upload-artifact@v3
        with:
          name: SaveMii-Aroma
          path: savemii.wuhb
          if-no-files-found: warn
      - name: Upload HBL version
        uses: actions/upload-artifact@v3
        with:
          name: SaveMii-HBL
          path: savemii.rpx
          if-no-files-found: warn
