name: CI-Release

on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches:
      - refactor
      - oop

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build artifacts
        run: |
          docker build . -t builder
          docker run --rm -v ${PWD}:/project builder make -j$(nproc)
      - name: Upload Aroma version
        uses: actions/upload-artifact@v3
        with:
          name: SaveMii-Aroma
          path: savemii.wuhb
          if-no-files-found: warn
      - name: Upload HBL version
        uses: actions/upload-artifact@v3
        with:
          name: SaveMii-HBL
          path: savemii.rpx
          if-no-files-found: warn
